# name: Build API Gateway Docker Image and Push

# on:
#     push:
#         branches:
#             - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout Code
#       uses: actions/checkout@v3

#     - name: Docker Build
#       run: |
#           sudo apt update
#           sudo apt install make docker.io -y

name: Build API Gateway Docker Image and Push

on:
    push:
        branches:
            - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Make for Makefile #(if needed)
      run: |
          sudo apt update
          sudo apt install make -y

    - name: Docker/Makefile Build
      run: |
          cd api-gateway
          make build
    # - name: Docker Build
    #   run: |
    #       cd api-gateway
    #       docker build -t api-gateway:v1.0 .
#              #   Assuming your Docker build is triggered via a Makefile
            
