name: Build API Gateway Docker Image and Push

on:
    push:
        branches:
            - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Docker Build
      run: |
          sudo apt update
          sudo apt install make docker.io -y

