name: Build and Push API Gateway Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Make for Makefile (if needed)
      run: |
        sudo apt update
        sudo apt install make -y

    - name: Docker/Makefile Build
      run: |
        cd api-gateway
        make build

    - name: Docker Login and Push
      run: |
        cd api-gateway
        make docker-login
        make push
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

# name: Build and Push API Gateway Docker Image

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout Code
#       uses: actions/checkout@v3

#     - name: Install Make for Makefile (if needed)
#       run: |
#           sudo apt update
#           sudo apt install make -y

#     - name: Docker/Makefile Build
#       run: |
#           cd api-gateway
#           make build

#     - name: Docker Login
#       run: |
#          cd api-gateway
#          make docker-login
#       env: 
#         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#         DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

#   push:
#     runs-on: ubuntu-latest
#     needs: deploy

#     steps:
#     - name: Checkout Code
#       uses: actions/checkout@v3

#     - name: Docker Push
#       run: |
#         cd api-gateway
#         make push
#       env:
#         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#         DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
#       # Pass DOCKER_REGISTRY only if necessary for a custom registry
#        # DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}




# name: Build API Gateway Docker Image and Push

# on:
#     push:
#         branches:
#             - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout Code
#       uses: actions/checkout@v3

#     - name: Docker Build
#       run: |
#           sudo apt update
#           sudo apt install make docker.io -y

# name: Build API Gateway Docker Image and Push

# on:
#     push:
#         branches:
#             - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout Code
#       uses: actions/checkout@v3

#     - name: Install Make for Makefile #(if needed)
#       run: |
#           sudo apt update
#           sudo apt install make -y

#     - name: Docker/Makefile Build
#       run: |
#           cd api-gateway
#           make build
#     # - name: Docker Build
#     #   run: |
#     #       cd api-gateway
#     #       docker build -t api-gateway:v1.0 .
# #              #   Assuming your Docker build is triggered via a Makefile
 
#     - name: Docker Login
#       run: |
#          cd api-gateway
#          make docker-login
#       env: 
#         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#         DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
#         DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
#   push:
#     runs-on: ubuntu-latest
#     needs: deploy
#     steps:
#     - name: Checkout Code
#       uses: actions/checkout@v3

#     - name: Docker Push
#       run: |
#         cd api-gateway
#         make push